name: Auto Update Android GSI

on:
  schedule:
    - cron: '0 0 * * 0'    # 每周日 UTC 00:00 运行
  workflow_dispatch:      # 支持手动触发

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    # 1. 下载 v1.0.0 模板（压缩版）
    - name: 下载 v1.0.0 模板镜像 System
      uses: robinraju/release-downloader@v1
      with:
        repository: ${{ github.repository }}
        tag: 'v1.0.0'
        fileName: 'system.img.xz'
    
    # 2. 解压并准备原始镜像
    - name: 解压模板镜像
      run: |
        mkdir -p original
        xz -d system.img.xz
        mv system.img original/system.img

    # 3. 安装必要的系统依赖
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        qemu-utils \
        unzip wget xz-utils cmake pkg-config \
        liblzma-dev liblz4-dev libbz2-dev zlib1g-dev \
        clang rustc cargo ninja-build
        sudo apt-get install -y android-sdk-libsparse-utils android-tools-adb

    # 4. 随机化机型 ↔ 厂商对
    - name: 随机化机型与厂商
      id: gen_device
      run: |
        declare -A DEVICE_MAP=(
          [Pixel_3]=Google   [Pixel_4]=Google
          [Galaxy_S10]=Samsung [Galaxy_S20]=Samsung
          [OnePlus_7]=OnePlus [OnePlus_8]=OnePlus
          [Mi_9]=Xiaomi       [Mi_10]=Xiaomi
          [Poco_F2]=Poco      [Redmi_Note_8]=Xiaomi
        )
        models=("${!DEVICE_MAP[@]}")
        idx=$(( RANDOM % ${#models[@]} ))
        MODEL="${models[$idx]}"
        MANUF="${DEVICE_MAP[$MODEL]}"
        IMEI="$(date +%s)"              # 以时间戳做简单 IMEI
        echo "MODEL=$MODEL"   >> $GITHUB_ENV
        echo "MANUF=$MANUF"   >> $GITHUB_ENV
        echo "IMEI=$IMEI"     >> $GITHUB_ENV

    # 5. 修改 system.img 的 build.prop
    - name: 编辑镜像（使用 qemu-nbd）
      run: |
        simg2img original/system.img raw-system.img
        sudo modprobe nbd max_part=8                  # 加载 NBD 模块
        sudo qemu-nbd --format raw --connect=/dev/nbd0 raw-system.img
        # 挂载第一个分区（通常是 nbd0p1）
        sudo mkdir -p /mnt/img
        sudo mount /dev/nbd0 /mnt/img
        # 修改 build.prop
        sudo sed -i "s/^persist\.radio\.imei=.*/persist.radio.imei=${IMEI}/" /mnt/img/build.prop
        sudo sed -i "s/^ro\.product\.model=.*/ro.product.model=${MODEL}/" /mnt/img/build.prop
        sudo sed -i "s/^ro\.product\.manufacturer=.*/ro.product.manufacturer=${MANUF}/" /mnt/img/build.prop
        # 卸载并断开
        sudo umount /mnt/img
        sudo fuser -v /dev/nbd0
        sudo fuser -k /dev/nbd0
        sudo qemu-nbd --disconnect /dev/nbd0
        sudo modprobe -r nbd
        sudo rmmod nbd || true
        mv raw-system.img original/system.img

    # 8. 多线程 XZ 压缩并准备发布
    - name: 压缩为 XZ
      run: |
        xz -T0 -z original/system.img
        mv original/system.img.xz system.img.xz

    # 9. 发布为新的 GitHub Release
    - name: 发布 Release 附件（XZ 格式）
      uses: softprops/action-gh-release@v1
      with:
        tag_name: weekly-${{ github.run_number }}
        name: GSI-with-Magisk-${{ github.run_number }}
        files: |
          system.img.xz
